server:
  port: 8334

spring:
  application:
    name: services

  datasource:
    url: jdbc:mysql://localhost:3306/HouseListings?useSSL=false&serverTimezone=UTC
    username: root
    password: peter
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: public
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

authentication:
  service:
    url: http://localhost:8331

platform:
  commission:
    provider: 0.20


gateway:
  secret: "Gv7kR2t0eJ0mQyqB1T8Vw3C4Z9lFh2rPp8bK0sXq7Jt4Wm9eD3Fq6Yv1Nn5Rc8Zd"


