server:
  port: 8333

spring:
  application:
    name: product-service

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: Gv7kR2t0eJ0mQyqB1T8Vw3C4Z9lFh2rPp8bK0sXq7Jt4Wm9eD3Fq6Yv1Nn5Rc8Zd

  datasource:
    url: jdbc:postgresql://localhost:5432/realestate
    username: admin
    password: admin@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: public
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

authentication:
  service:
    url: http://localhost:8331

videos:
  folder: videos
  base-url: http://localhost:8333/videos/

gateway:
  secret: "Gv7kR2t0eJ0mQyqB1T8Vw3C4Z9lFh2rPp8bK0sXq7Jt4Wm9eD3Fq6Yv1Nn5Rc8Zd"

bookings:
  booking-fee: 5
  visit-fee: 1

mpesa:
  business-shortcode: 174379
  party-b: 174379
  transaction-type: CustomerPayBillOnline
  passkey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
  callback-url: https://your-ngrok-or-server-url.com/api/mpesa/callback
  consumer-key: GYAY9C3wmlgIgjfOAGigrqcVmsvZNM0TkAIXIG2lcRcvGG0o
  consumer-secret: voXgzGFfgZZ1KxpTq0sH09leOpt60QCuesqY8MjIBUb29msHQ7JDyCEGuL5E2LCY
  stk-url: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest

pesapal:
  consumer-key: ryJSvd0e2/rwOmXvRhb2gvpn6tWgFXgq
  consumer-secret: /3+05mCCUvj1VQHdL7it99X7fd8=
  live-authentication-url: https://pay.pesapal.com/v3/api/Auth/RequestToken
  submit-request-url: https://pay.pesapal.com/v3/api/Transactions/SubmitOrderRequest
  currency: KES
  cancellation-url: ""
  callback-url: https://brittani-isoglossal-suavely.ngrok-free.dev/api/products/payment/callback
  notification-id: 0a9968b5-2b2b-4488-a0fa-dae04fec26b4
  redirect-mode: ""
  ipn-url: https://brittani-isoglossal-suavely.ngrok-free.dev/api/products/payment/callback
  ipn-registration-url: https://pay.pesapal.com/v3/api/URLSetup/RegisterIPN


